### ISSUE TITLE
您好 请教下 这个可以用在生产环境吗？

### ISSUE THREAD

**Issue by LoveChina-3000** [JelinYao/AsyncIPC#1]
您好 大佬 请教下 这个可以用在生产环境吗？

**Comment by JelinYao** [comment]
可以的，这个我自己在几个项目上用过。

**Comment by LoveChina-3000** [comment]
您好 请问下，需要如何修改，服务端在客户端断开后，可以继续等待新的客户端连接呀？现在是客户端连接后，关闭客户端，服务端也退出了

**Comment by JelinYao** [comment]
断开后需要重连，先调用Exit()把原来的资源都释放掉，再重新走一遍建立连接的过程：Create(...)。

**Comment by LoveChina-3000** [comment]
谢谢大佬
